version: "3"
services: 
  resize-image:
    container_name: resize-images
    build: .
    ports: 
      - "80:3000"
    restart: always
    image: resize-images
    volumes:
      - ./src:/usr/src/app/src